### ISSUE TITLE
No information on how to change or enable Wake-Up  phrase 

### ISSUE THREAD

**Issue by koolkarni** [soundhound/houndify-sdk-go#9]

**Comment by mehul-p** [comment]
Houndify offers support for the default wakeup phrase “Ok Hound.”  It hasn’t been integrated in the Go SDK yet, however you can enable it using other SDKs such as ~~Web or Python~~ Android and iOS SDK.

We also offer changing the wakeup phrase from “Ok Hound” to something like the name of your solution. It does require additional effort and so there is a onetime fee. We recommend you to get started with the default wakeup phrase initially and contact us at support@houndify.com when you are ready to customize the wakeup phrase for your solution.

**Comment by koolkarni** [comment]
can you please provide me a document or web link which shows how i can enable default wakeup phrase.
for nodejs SDk client

**Comment by mehul-p** [comment]
Turns out our Android and iOS SDKs include support for enabling the wakeup phrase "OK Hound". I'll update my previous response with the correction. You can checkout the SDKs at https://www.houndify.com/sdks#android and https://www.houndify.com/sdks#ios
